site_name: Bar Assistant Documentation
repo_url: https://github.com/karlomikus/bar-assistant
site_url: https://bar-assistant.github.io/docs
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.png
  custom_dir: overrides
  features:
    - content.code.annotate
    # - content.action.edit
    - navigation.tabs
  palette:
    # Palette toggle for light mode
    - scheme: indigo
      accent: pink
      primary: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      accent: pink
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - 'index.md'
  - Setup:
    - 'setup/index.md'
    - 'setup/updating.md'
    - 'setup/backups.md'
  - 'usage/index.md'
  - 'faq.md'
  # - 'changelog.md'

extra:
  analytics:
    provider: custom
