site_name: Bar Assistant
repo_url: https://github.com/karlomikus/bar-assistant
site_url: https://bar-assistant.github.io/docs
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.png
  custom_dir: overrides
  features:
    - content.code.annotate
    # - content.action.edit
    - navigation.tabs
  palette:
    # Palette toggle for light mode
    - scheme: black
      accent: pink
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      accent: pink
      primary: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - index.md
  - Setup:
    - 'setup/index.md'
    - 'setup/source-install.md'
    - 'setup/mailing.md'
    - 'setup/development.md'
    - 'setup/migrate-to-15.md'
    - 'setup/migrate-to-30.md'
    - 'setup/migrate-to-40.md'
  - 'data.md'
  - 'faq.md'
  - "OpenAPI Spec": https://api.barassistant.app/docs

extra:
  analytics:
    provider: custom
